config/routes.rb
Rails.application.routes.draw do
  resources :talks do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/talk.rb
class Talk < ApplicationRecord
  validates :content, presence: true
  validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]
  def index
    @talks = Talk.all
  end
  def new
    @talk = Talk.new
  end
  def create
    @talk = Talk.new(talk_params)
    if params[:back]
      render :new
    else
      if @talk.save
        redirect_to talks_path, notice: "トークを作成しました！"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @talk.update(talk_params)
      redirect_to talks_path, notice: "トークを編集しました！"
    else
      render :edit
    end
  end
  def destroy
    @talk.destroy
    redirect_to talks_path, notice: "トークを削除しました！"
  end
  def confirm
    @talk = Talk.new(talk_params)
    render :new if @talk.invalid?
  end
  private
  def talk_params
    params.require(:talk).permit(:content)
  end
  def set_talk
    @talk = Talk.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_talks_path
    elsif action_name == 'edit'
      talk_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/talks/_form.html.erb
<%= form_with(model: @talk, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= @talk.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="talk_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to 'Talks一覧画面に戻る', talks_path %>

app/views/talks/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @talk, url: talks_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @talk.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/talks/edit.html.erb
<h2>トークを作成する</h2>
<%= render 'form' %>

app/views/talks/index.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Talk</title>
    <link rel="stylesheet" href="../../css/normalize.css">
  </head>
  <body>
    <div id="wrapper">
      <header>
        <div class="header_logo">Talk</div>
      </header>
      <h1>トーク 一覧</h1>
      <p><%= notice %></p>
      <table>
        <tr>
          <th>内容</th>
        </tr>
      <% @talks.each do |talk| %>
        <tr>
          <td><%= talk.content %></td>
          <td><%= link_to 'トークを確認する', talk_path(talk.id) %></td>
          <td><%= link_to "トークを編集する", edit_talk_path(talk.id) %></td>
          <td><%= link_to 'トークを削除する', talk_path(talk.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
        </tr>
      <% end %>
      </table>
      <br>
      <%= link_to '新しく投稿する', new_talk_path %>
      <footer>
        <p>©︎2020 Copyright Nanako Kan</p>
      </footer>
    </div>
  </body>
</html>

app/views/talks/new.html.erb
<%= form_with(model: @talk, local: true) do |form| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= @talk.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="talk_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to 'Talks一覧画面に戻る', talks_path %>

app/views/talks/show.html.erb
<h1>トーク確認画面</h1>
<p>内容: <%= @talk.content %></p>